from .matplotlib_setup import ensure_matplotlib_config_dir
ensure_matplotlib_config_dir()

from .api import classify_spectrum, fit_phoenix_spectrum, fit_stellar_spectrum
from .help import (
    describe_public_function,
    format_public_function_help,
    list_public_functions,
)
from .defaults import (
    FitSetup,
    PhoenixFitDefaults,
    clip_grid_to_bounds,
    prepare_phoenix_fit_kwargs,
    suggest_fit_setup,
    spectrum_wavelength_range,
    suggest_classification_branches,
    suggest_phoenix_fit_defaults,
)
from .results import (
    PhoenixFitDiagnostics,
    PhoenixFitResult,
    build_fit_quality_report,
    compare_fits,
    compare_fit_results,
    describe_quality_flags,
    format_fit_quality_report,
)
from .linefitting import (
    LineSpec,
    LineFitConfig,
    LineFitResult,
    fit_line,
    fit_lines,
    known_line_spec,
)
from .plotting import (
    plot_diagnostic_windows,
    plot_fit_referee,
    plot_line_fit,
    plot_model_line_windows,
    plot_spectrum,
    plot_spectrum_audit,
    plot_xsl_validation_payload,
)
from .diagnostics import (
    KNOWN_RESIDUAL_WINDOWS,
    annotate_nonstellar_features,
    diagnose_known_residual_windows,
)
from .diagnostic_windows import (
    DEFAULT_DIAGNOSTIC_ROLES,
    DIAGNOSTIC_WINDOW_CATALOG,
    DiagnosticWindow,
    build_diagnostic_window_combinations,
    diagnostic_window_catalog,
    fit_regions_from_combination,
    format_diagnostic_window_table,
    select_diagnostic_windows,
)
from .diagnostic_window_comparison import (
    build_diagnostic_window_comparison_plan,
    evaluate_diagnostic_window_common_evaluation,
    evaluate_diagnostic_window_holdout,
    plot_diagnostic_window_comparison,
    run_diagnostic_window_comparison,
    write_diagnostic_window_comparison_csv,
    write_diagnostic_window_comparison_json,
)
from .branch_quickscan import (
    build_branch_quickscan_plan,
    plot_branch_quickscan,
    run_branch_quickscan,
    summarize_branch_fit_stability,
    write_branch_quickscan_csv,
    write_branch_quickscan_json,
)
from .recipes import (
    normalize_segment_sidebands,
    normalize_segments_sidebands,
    sdss_quicklook_resolution_assumption,
)
from .preprocessing import (
    NONSTELLAR_FEATURES,
    OPTICAL_DIB_DIAGNOSTIC_FEATURES,
    OPTICAL_TELLURIC_DIAGNOSTIC_FEATURES,
    ExclusionMaskSpec,
    MaskBundle,
    archive_exclusion_masks,
    archive_exclusion_masks_for_segment,
    archive_mask_catalog,
    archive_mask_summary_for_segment,
    artifact_exclusion_mask_from_segment,
    audit_spectrum_for_fit,
    build_mask,
    combine_exclusion_masks,
    dilate_boolean_mask,
    exclusion_mask,
    known_feature_masks,
    nonstellar_feature_mask,
    nonstellar_feature_masks,
    nonstellar_feature_metadata,
    nonstellar_feature_regions,
    overlapping_nonstellar_features,
    publication_readiness_audit,
    readiness_flag_actions,
    broad_telluric_catalog_fallback_mask,
    telluric_transmission_exclusion_mask,
)
from .waveutils import convert_segment_wavelength_medium, convert_wavelength_medium
from .fitting import FitProgressEvent
from .io import (
    InstrumentInfo,
    SpectrumCollection,
    SpectrumSegment,
    get_instrument_info,
    list_instruments,
    read_gaia_benchmark_ascii,
    read_sdss_spec,
    read_spectrum,
    read_uves_pop_ascii,
    sdss_wdisp_to_resolution_descriptor,
)

__all__ = [
    "fit_phoenix_spectrum", "fit_stellar_spectrum", "classify_spectrum",
    "describe_public_function", "format_public_function_help",
    "list_public_functions",
    "read_spectrum", "list_instruments", "get_instrument_info",
    "InstrumentInfo", "read_uves_pop_ascii", "read_gaia_benchmark_ascii",
    "read_sdss_spec",
    "sdss_wdisp_to_resolution_descriptor",
    "SpectrumSegment", "SpectrumCollection",
    "ensure_matplotlib_config_dir",
    "PhoenixFitDiagnostics", "PhoenixFitResult",
    "FitSetup", "PhoenixFitDefaults", "clip_grid_to_bounds",
    "prepare_phoenix_fit_kwargs", "spectrum_wavelength_range",
    "suggest_fit_setup", "suggest_classification_branches",
    "suggest_phoenix_fit_defaults",
    "build_fit_quality_report", "compare_fit_results", "compare_fits",
    "describe_quality_flags",
    "format_fit_quality_report",
    "LineSpec", "LineFitConfig", "LineFitResult", "fit_line", "fit_lines",
    "known_line_spec",
    "plot_fit_referee", "plot_line_fit", "plot_model_line_windows", "plot_spectrum",
    "plot_diagnostic_windows", "plot_spectrum_audit", "plot_xsl_validation_payload",
    "KNOWN_RESIDUAL_WINDOWS", "annotate_nonstellar_features",
    "diagnose_known_residual_windows",
    "DEFAULT_DIAGNOSTIC_ROLES", "DIAGNOSTIC_WINDOW_CATALOG",
    "DiagnosticWindow", "build_diagnostic_window_combinations",
    "diagnostic_window_catalog", "fit_regions_from_combination",
    "format_diagnostic_window_table", "select_diagnostic_windows",
    "build_diagnostic_window_comparison_plan",
    "evaluate_diagnostic_window_common_evaluation",
    "evaluate_diagnostic_window_holdout",
    "run_diagnostic_window_comparison", "plot_diagnostic_window_comparison",
    "write_diagnostic_window_comparison_csv",
    "write_diagnostic_window_comparison_json",
    "build_branch_quickscan_plan", "run_branch_quickscan",
    "plot_branch_quickscan", "summarize_branch_fit_stability",
    "write_branch_quickscan_csv", "write_branch_quickscan_json",
    "normalize_segment_sidebands", "normalize_segments_sidebands",
    "sdss_quicklook_resolution_assumption",
    "ExclusionMaskSpec", "MaskBundle", "build_mask", "archive_exclusion_masks",
    "archive_exclusion_masks_for_segment", "archive_mask_catalog",
    "archive_mask_summary_for_segment", "artifact_exclusion_mask_from_segment",
    "audit_spectrum_for_fit",
    "publication_readiness_audit",
    "readiness_flag_actions",
    "combine_exclusion_masks", "dilate_boolean_mask",
    "exclusion_mask",
    "NONSTELLAR_FEATURES", "OPTICAL_DIB_DIAGNOSTIC_FEATURES",
    "OPTICAL_TELLURIC_DIAGNOSTIC_FEATURES",
    "known_feature_masks", "nonstellar_feature_mask", "nonstellar_feature_masks",
    "nonstellar_feature_metadata", "nonstellar_feature_regions",
    "overlapping_nonstellar_features", "broad_telluric_catalog_fallback_mask",
    "telluric_transmission_exclusion_mask",
    "convert_wavelength_medium", "convert_segment_wavelength_medium",
    "FitProgressEvent",
]
